spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sales
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: create
    generate-ddl: true
    hibernate:
      ddl-auto: none


#spring:
#  datasource:
#    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
#    username: sa
#    password: ''
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        hbm2ddl:
#          auto: create
#    generate-ddl: true
#    hibernate:
#      ddl-auto: none